<?php
/**
 * Implements hook_action_info
 */
function ekono_custom_actions_action_info(){
  return array(
    'ekono_custom_actions_mark_as_recommended' => array(
      'type' => 'node',
      'label' => t('Marcar productos como recomendados'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
    'ekono_custom_actions_mark_as_not_recommended' => array(
      'type' => 'node',
      'label' => t('Marcar productos como no recomendados'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}

/**
 * Action for ekono_custom_actions_mark_as_recommended
 */
function ekono_custom_actions_mark_as_recommended(&$node, $context){
  if(strpos($node->type, 'producto_art_') === 0){
    $node->field_recomendado[LANGUAGE_NONE][0]['value'] = 1;
  }
}

/**
 * Action for ekono_custom_actions_mark_as_not_recommended
 */
function ekono_custom_actions_mark_as_not_recommended(&$node, $context){
  if(strpos($node->type, 'producto_art_') === 0){
    $node->field_recomendado[LANGUAGE_NONE][0]['value'] = 0;
  }
}
